LivrariaControleEmprestimo.WEB/Models/EmprestimoViewModel.cs
using LivrariaControleEmprestimo.DATA.Models;

namespace LivrariaControleEmprestimo.WEB.Models
{
    public class EmprestimoViewModel
    {
        public Livro? oLivro { get; set; }
        public Cliente? oCliente { get; set; }
        public DateTime? dataEmprestimo { get; set; }
        public DateTime? dataEntrega { get; set; }
        public int idCliente { get; set; }
        public int idLivro { get; set; }
        public List<Cliente> oListCliente { get; set; } 
        public List<Livro> oListLivro { get; set; }    
    }
}

LivrariaControleEmprestimo.WEB/Models/ErrorViewModel.cs
namespace LivrariaControleEmprestimo.WEB.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LivrariaControleEmprestimo.WEB/Controllers/ClienteController.cs
using LivrariaControleEmprestimo.DATA.Models;
using LivrariaControleEmprestimo.DATA.Services;
using Microsoft.AspNetCore.Mvc;

namespace LivrariaControleEmprestimo.WEB.Controllers
{
    public class ClienteController : Controller
    {
        private ClienteService oClienteService = new ClienteService();

        public IActionResult Index()
        {
            List<Cliente> oListCliente = oClienteService.oRepositoryCliente.SelecionarTodos();
            return View(oListCliente);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Cliente model)
        {
            if(!ModelState.IsValid)
                return View();

            oClienteService.oRepositoryCliente.Incluir(model);

            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            Cliente oCliente = oClienteService.oRepositoryCliente.SelecionarPk(id);

            return View(oCliente);
        }
        public IActionResult Edit(int id)
        {
            Cliente oCliente = oClienteService.oRepositoryCliente.SelecionarPk(id);

            return View(oCliente);
        }

        [HttpPost]
        public IActionResult Edit(Cliente model)
        {
            Cliente oCliente = oClienteService.oRepositoryCliente.Alterar(model);

            int id = oCliente.Id;

            return RedirectToAction("Details", new { id });
        }

        public IActionResult Delete(int id)
        {
            oClienteService.oRepositoryCliente.Excluir(id); 
            
            return RedirectToAction("Index"); 
        }
    }
}

LivrariaControleEmprestimo.WEB/Controllers/EmprestimosController.cs
using LivrariaControleEmprestimo.DATA.Models;
using LivrariaControleEmprestimo.DATA.Services;
using LivrariaControleEmprestimo.WEB.Models;
using Microsoft.AspNetCore.Mvc;

namespace LivrariaControleEmprestimo.WEB.Controllers
{
    public class EmprestimosController : Controller
    {
        private LivroClienteEmprestimoService _service = new LivroClienteEmprestimoService();
        public IActionResult Index()
        {
            List<VwLivroClienteEmprestimo> oListVwLivroClienteEmprestimo = _service.oRepositoryLivroClienteEmprestimo.SelecionarTodos();
            return View(oListVwLivroClienteEmprestimo);
        }

        public IActionResult Create()
        {
            EmprestimoViewModel oEmprestimoViewModel = new EmprestimoViewModel();
          
            List<Livro> oListLivro = _service.oRepositoryLivro.SelecionarTodos();   
            List<Cliente> oListCliente = _service.oRepositoryCliente.SelecionarTodos();

            oEmprestimoViewModel.oListCliente = oListCliente;
            oEmprestimoViewModel.oListLivro = oListLivro;
            
            return View(oEmprestimoViewModel);
        }
    }
}

LivrariaControleEmprestimo.WEB/Controllers/HomeController.cs
using LivrariaControleEmprestimo.WEB.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LivrariaControleEmprestimo.WEB.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LivrariaControleEmprestimo.WEB/Controllers/LivroController.cs
using LivrariaControleEmprestimo.DATA.Models;
using LivrariaControleEmprestimo.DATA.Services;
using Microsoft.AspNetCore.Mvc;

namespace LivrariaControleEmprestimo.WEB.Controllers
{
    public class LivroController : Controller
    {
        private LivroService oLivroService = new LivroService();

        public IActionResult Index()
        {
            List<Livro> oListLivro = oLivroService.oRepositoryLivro.SelecionarTodos();
            return View(oListLivro);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Livro model)
        {
            if (!ModelState.IsValid)
                return View();

            oLivroService.oRepositoryLivro.Incluir(model);

            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            Livro oLivro = oLivroService.oRepositoryLivro.SelecionarPk(id);

            return View(oLivro);
        }
        public IActionResult Edit(int id)
        {
            Livro oLivro = oLivroService.oRepositoryLivro.SelecionarPk(id);

            return View(oLivro);
        }

        [HttpPost]
        public IActionResult Edit(Livro model)
        {
            Livro oLivro = oLivroService.oRepositoryLivro.Alterar(model);

            int id = oLivro.Id;

            return RedirectToAction("Details", new { id });
        }

        public IActionResult Delete(int id)
        {
            oLivroService.oRepositoryLivro.Excluir(id);

            return RedirectToAction("Index");
        }
    }
}

LivrariaControleEmprestimo.WEB/Views/Cliente/Create.cshtml
@model LivrariaControleEmprestimo.DATA.Models.Cliente

@{
    ViewData["Title"] = "Create";
}

<h1>Novo Cliente</h1>

<h4>Preencha os campos abaixo para incluir um novo cliente.</h4>
<hr />
<div>
    <a class="btn btn-primary" asp-action="Index">Voltar</a>
</div>
<br />
<div class="row">
    <div class="col-md">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <br />
            <div class="card">
                <div class="card-header">Informações Pessoais</div>
                <div class="card-body">
                    <div class="form-group col-md">
                        <label asp-for="CliCpf" class="control-label"></label>
                        <input asp-for="CliCpf" class="form-control" />
                        <span asp-validation-for="CliCpf" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md">
                        <label asp-for="CliNome" class="control-label"></label>
                        <input asp-for="CliNome" class="form-control" />
                        <span asp-validation-for="CliNome" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <br />
            <div class="card">
                <div class="card-header">Endereço</div>
                <div class="card-body row">
                    <div class="form-group col-md">
                        <label asp-for="CliEndereco" class="control-label"></label>
                        <input asp-for="CliEndereco" class="form-control" />
                        <span asp-validation-for="CliEndereco" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CliCidade" class="control-label"></label>
                        <input asp-for="CliCidade" class="form-control" />
                        <span asp-validation-for="CliCidade" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md">
                        <label asp-for="CliBairro" class="control-label"></label>
                        <input asp-for="CliBairro" class="form-control" />
                        <span asp-validation-for="CliBairro" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md">
                        <label asp-for="CliNumero" class="control-label"></label>
                        <input asp-for="CliNumero" class="form-control" />
                        <span asp-validation-for="CliNumero" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <br />
            <div class="card">
                <div class="card-header">Contato</div>
                <div class="card-body">
                    <div class="col-md">
                        <div class="form-group">
                            <label asp-for="CliTelefoneCelular" class="control-label"></label>
                            <input asp-for="CliTelefoneCelular" class="form-control" />
                            <span asp-validation-for="CliTelefoneCelular" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md">
                        <div class="form-group">
                            <label asp-for="CliTelefoneFixo" class="control-label"></label>
                            <input asp-for="CliTelefoneFixo" class="form-control" />
                            <span asp-validation-for="CliTelefoneFixo" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Incluir" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

LivrariaControleEmprestimo.WEB/Views/Cliente/Details.cshtml
@model LivrariaControleEmprestimo.DATA.Models.Cliente

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Cliente</h4>
    <hr />

    <div class="card">
        <div class="card-header">Informações Pessoais</div>
        <div class="card-body">
            <div class="form-group col-md">
                <label>@Html.DisplayNameFor(model => model.CliCpf)</label>
                <input disabled class="form-control" value="@Html.DisplayFor(model => model.CliCpf)" />
            </div>
            <div class="form-group col-md">
                <label>@Html.DisplayNameFor(model => model.CliNome)</label>
                <input disabled class="form-control" value="@Html.DisplayFor(model => model.CliNome)" />
            </div>
        </div>
    </div>
    <br />
    <div class="card">
        <div class="card-header">Endereço</div>
        <div class="card-body row">
            <div class="form-group col-md">
                <label>@Html.DisplayNameFor(model => model.CliCidade)</label>
                <input disabled class="form-control" value="@Html.DisplayFor(model => model.CliCidade)" />
            </div>
            <div class="form-group">
                <label>@Html.DisplayNameFor(model => model.CliBairro)</label>
                <input disabled class="form-control" value="@Html.DisplayFor(model => model.CliBairro)" />
            </div>
            <div class="form-group col-md">
                <label>@Html.DisplayNameFor(model => model.CliEndereco)</label>
                <input disabled class="form-control" value="@Html.DisplayFor(model => model.CliEndereco)" />
            </div>
            <div class="form-group col-md">
                <label>@Html.DisplayNameFor(model => model.CliNumero)</label>
                <input disabled class="form-control" value="@Html.DisplayFor(model => model.CliNumero)" />
            </div>
        </div>
    </div>
    <br />
    <div class="card">
        <div class="card-header">Contato</div>
        <div class="card-body">
            <div class="col-md">
                <div class="form-group">
                    <label>@Html.DisplayNameFor(model => model.CliTelefoneCelular)</label>
                    <input disabled class="form-control" value="@Html.DisplayFor(model => model.CliTelefoneCelular)" />
                </div>
            </div>
            <div class="col-md">
                <div class="form-group">
                    <label>@Html.DisplayNameFor(model => model.CliTelefoneFixo)</label>
                    <input disabled class="form-control" value="@Html.DisplayFor(model => model.CliTelefoneFixo)" />
                </div>
            </div>
        </div>
    </div>

</div>
<br />
<div>
    <a asp-action="Edit" class="btn btn-success" asp-route-id="@Model?.Id">Alterar</a>
    <a class="btn btn-primary" asp-action="Index">Voltar</a>
</div>

LivrariaControleEmprestimo.WEB/Views/Cliente/Edit.cshtml
@model LivrariaControleEmprestimo.DATA.Models.Cliente

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Edite os dados abaixo</h4>
<hr />
<div class="row">
    <div class="col-md">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <br />
            <div hidden class="form-group col-md">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
            </div>
            <div class="card">
                <div class="card-header">Informações Pessoais</div>
                <div class="card-body">
                    <div class="form-group col-md">
                        <label asp-for="CliCpf" class="control-label"></label>
                        <input asp-for="CliCpf" class="form-control" />
                        <span asp-validation-for="CliCpf" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md">
                        <label asp-for="CliNome" class="control-label"></label>
                        <input asp-for="CliNome" class="form-control" />
                        <span asp-validation-for="CliNome" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <br />
            <div class="card">
                <div class="card-header">Endereço</div>
                <div class="card-body row">
                    <div class="form-group col-md">
                        <label asp-for="CliEndereco" class="control-label"></label>
                        <input asp-for="CliEndereco" class="form-control" />
                        <span asp-validation-for="CliEndereco" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CliCidade" class="control-label"></label>
                        <input asp-for="CliCidade" class="form-control" />
                        <span asp-validation-for="CliCidade" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md">
                        <label asp-for="CliBairro" class="control-label"></label>
                        <input asp-for="CliBairro" class="form-control" />
                        <span asp-validation-for="CliBairro" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md">
                        <label asp-for="CliNumero" class="control-label"></label>
                        <input asp-for="CliNumero" class="form-control" />
                        <span asp-validation-for="CliNumero" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <br />
            <div class="card">
                <div class="card-header">Contato</div>
                <div class="card-body">
                    <div class="col-md">
                        <div class="form-group">
                            <label asp-for="CliTelefoneCelular" class="control-label"></label>
                            <input asp-for="CliTelefoneCelular" class="form-control" />
                            <span asp-validation-for="CliTelefoneCelular" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md">
                        <div class="form-group">
                            <label asp-for="CliTelefoneFixo" class="control-label"></label>
                            <input asp-for="CliTelefoneFixo" class="form-control" />
                            <span asp-validation-for="CliTelefoneFixo" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Incluir" class="btn btn-success" />
                <a class="btn btn-primary" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LivrariaControleEmprestimo.WEB/Views/Cliente/Index.cshtml
@model IEnumerable<LivrariaControleEmprestimo.DATA.Models.Cliente>

@{
    ViewData["Title"] = "Index";
}

<h1>Clientes</h1>

<p>
    <a class="btn btn-primary" asp-action="Create">Novo cliente</a>
</p>
<table id="myTable" class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CliCpf)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CliNome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CliTelefoneCelular)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CliTelefoneFixo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CliCpf)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CliNome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CliTelefoneCelular)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CliTelefoneFixo)
                </td>
                <td class="col col-md-3">
                    <a asp-action="Edit" class="btn btn-success m-1" asp-route-id="@item.Id">Alterar</a>
                    <a asp-action="Details" class="btn btn-primary m-1" asp-route-id="@item.Id">Detalhes</a>

                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-danger m-1" data-toggle="modal" data-target="#exampleModal-@item.Id">
                        Excluir
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal-@item.Id" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Excluir cliente</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    Deseja realmente excluir o cliente @item.CliNome ?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Não</button>
                                    <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.Id">Sim</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts{
    <script>
        $(document).ready(function () {
            $('#myTable').DataTable({
                language: {
                    url: 'https://cdn.datatables.net/plug-ins/1.11.5/i18n/Portuguese-Brasil.json',
                },
            });
        });
    </script>


    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
}

LivrariaControleEmprestimo.WEB/Views/Emprestimos/Index.cshtml
@model IEnumerable<LivrariaControleEmprestimo.DATA.Models.VwLivroClienteEmprestimo>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table id="myTable" class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CliNome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LivroNome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LceIdLivro)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LceIdCliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LceDataEmprestimo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LceDataEntrega)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LceEntregue)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CliNome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LivroNome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LceIdLivro)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LceIdCliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LceDataEmprestimo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LceDataEntrega)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LceEntregue)
            </td>
                <td class="col col-md-3">
                    <a asp-action="Edit" class="btn btn-success m-1" asp-route-id="@item.Id">Alterar</a>
                    <a asp-action="Details" class="btn btn-primary m-1" asp-route-id="@item.Id">Detalhes</a>

                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-danger m-1" data-toggle="modal" data-target="#exampleModal-@item.Id">
                        Excluir
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal-@item.Id" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Excluir cliente</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    Deseja realmente excluir o cliente @item.CliNome ?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Não</button>
                                    <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.Id">Sim</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
        </tr>
}
    </tbody>
</table>

@section Scripts{
    <script>
        $(document).ready(function () {
            $('#myTable').DataTable({
                language: {
                    url: 'https://cdn.datatables.net/plug-ins/1.11.5/i18n/Portuguese-Brasil.json',
                },
            });
        });
    </script>


    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
}

LivrariaControleEmprestimo.WEB/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

LivrariaControleEmprestimo.WEB/Views/Livro/Create.cshtml
@model LivrariaControleEmprestimo.DATA.Models.Livro

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Livro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LivroNome" class="control-label"></label>
                <input asp-for="LivroNome" class="form-control" />
                <span asp-validation-for="LivroNome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LivroAutor" class="control-label"></label>
                <input asp-for="LivroAutor" class="form-control" />
                <span asp-validation-for="LivroAutor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LivroEditora" class="control-label"></label>
                <input asp-for="LivroEditora" class="form-control" />
                <span asp-validation-for="LivroEditora" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LivroAnoPublicacao" class="control-label"></label>
                <input asp-for="LivroAnoPublicacao" class="form-control" />
                <span asp-validation-for="LivroAnoPublicacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LivroEdicao" class="control-label"></label>
                <input asp-for="LivroEdicao" class="form-control" />
                <span asp-validation-for="LivroEdicao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LivrariaControleEmprestimo.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Emprestimo Livro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LivrariaControleEmprestimo.WEB.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LivrariaControleEmprestimo.WEB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Emprestimos" asp-action="Index">Emprestimos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Livro" asp-action="Index">Livros</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Emprestimo Livros
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>